cliff_detector:
  ros__parameters:
    output_frame_id: oak-d-base-frame
    rate: 10
    range_min: 0.2
    range_max: 20.0
    sensor_mount_height: 0.1612
    sensor_tilt_angle: 15.0

    publish_depth: true
    cam_model_update: true
    used_depth_height: 720
    block_size: 16
    block_points_thresh: 3
    depth_img_step_row: 16
    depth_img_step_col: 16
    ground_margin: 0.05