 
name: DepthAI ROS Examples CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:

  style:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Clang-Format lint
      
      uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: '.'
        extensions: 'h,hpp,c,cpp'
        clangFormatVersion: 10
